---
- name: Deploy static site to EC2
  hosts: all
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy app files to web root
      copy:
        src: ../App/
        dest: /var/www/html/
        remote_src: yes
        mode: '0644'

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: true
